### ISSUE TITLE
Namespaces based on current path

### ISSUE THREAD

**Issue by jtojnar** [lesphp/psr4-converter#1]
Using the following command on https://github.com/ogioncz/eudyptes,

```ShellSession
vendor/bin/psr4-converter map -m /tmp/.psr4-converter.json --underscore-conversion --ignore-namespaced-underscore --ignore-path="bootstrap.php" -- "App" app/
```

it appears that the tool would move files around based on existing namespaces:

```json
{
    "originalName": "PostRevisionMapper",
    "newName": "PostRevisionMapper",
    "componentStmtClasses": null,
    "originalFile": "…\/app\/model\/orm\/post_revision\/PostRevisionMapper.php",
    "originalNamespace": "App\\Model",
    "newNamespace": "App\\_\\Model",
    "targetFile": "App\/_\/Model\/PostRevisionMapper.php",
    "targetFileWithoutVendor": "_\/Model\/PostRevisionMapper.php",
    "stmtClass": "PhpParser\\Node\\Stmt\\Class_",
    "exclusive": true,
    "classLike": true,
    "risky": false,
    "details": "class App\\Model\\PostRevisionMapper"
}
```

I would like to change the namespace based on file location (converted to camel-case) – for example, `app/model/orm/post_revision/PostRevisionMapper` would have a namespace `App\Model\Orm\PostRevision`.

Do you think this makes sense to support? Would you accept pull requests adding that as an option?

**Comment by lainosantos** [comment]
@jtojnar, This tool didn't support path based conversion, but it makes sense to support it. I created a pre-release 0.4.0 with this support. Can you test it?

Feel free to submit some PR.

**Comment by jtojnar** [comment]
Thanks for the quick implementation. I tested it and while it mostly works there are some rough edges.

```ShellSession
composer create-project lesphp/psr4-converter
psr4-converter/bin/psr4-converter map -m /tmp/.psr4-converter.json --underscore-conversion --ignore-namespaced-underscore --ignore-path="bootstrap.php" --path-based-conversion --force-names-camelcase -- "App" app/
```

1. Trying to move convert files in-place using `psr4-converter/bin/psr4-converter convert /tmp/.psr4-converter.json --ignore-vendor-path --allow-risky -- app`, the old files remain.

	Not sure about the ideal solution, though.

	- I could use a different directory (e.g. `app4`), remove the old one and then rename the new one to `app/` but that also removes non-PHP/ignored paths.
	- The tool could rename the files when `srcPath` is the same between `convert` and `map` invocations.
		- Probably should include a check if the directory is not dirty when using Git, otherwise it could get mixed with other changes.

2. Since Git does not track file renames but uses heurictics based on file contents, if the file diff is significant enough, comitting the changes will break Git history.
	- Perhaps we should add a `--commit-renames-first` that would run `git mv` on the renamed files and then `git commit` so that the renaming is happens separately from Git’s perspective.
		- Or if we do not want to think about writing a commit message, we could name the option `--stage-renames` and skip the commit part.
		- Again, we should probably check that the tree is not dirty.
3. No way to fix references in tests?
	- [Nette Tester](https://tester.nette.org/) prefers using `.phpt` file extension.
	- Even if I rename the tests, `psr4-converter/bin/psr4-converter map -m /tmp/.psr4-converter-tests.json --underscore-conversion --ignore-namespaced-underscore --ignore-path="unit/bootstrap.php" --path-based-conversion --force-names-camelcase -- "Tests" tests/` will fail to parse them because they contain some non-class code:
		```
		unit/ChatFormatterTest.php   12:12   Map error, unexpected T_VARIABLE on line 12
		unit/FormatterTest.php       15:15   Map error, unexpected T_VARIABLE on line 15
		```
4. The converter changes formatting during. While this is to be expected to a degree during any code transformations and user should run formatter after conversion, some aspects could surely be preserved (e.g. trailing commas in arrays and function arguments – PHP-CS-Fixer [will not](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/f26517a070589ebb88b1de6466e3762dcb43198f/doc/rules/basic/no_trailing_comma_in_singleline.rst) [be able](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/f26517a070589ebb88b1de6466e3762dcb43198f/doc/rules/control_structure/trailing_comma_in_multiline.rst) to return to the previous formatting when the converter compresses a structure to single line and removes the trailing comma, see an [example](https://github.com/ogioncz/eudyptes/pull/90/files#diff-af69015238a305e2ab59a3131a734eea228513476777572395e3c104d5e8c0d7R21)).

**Comment by lainosantos** [comment]
Hi @jtojnar.

About the in-place conversion, there is not yet an option in the convert command for that. The reason is that such a conversion would have to deal with conflicts and would add a lot of complexity to the conversion process. For example, a conversion of a file could result in overwriting another file that is yet to be converted, which would cause checksum errors and there would be no way to recover the previous source anymore. I'm not sure it's a good solution. One possibility I've been looking into is a command that does just that: delete affected files from src. This would give more flexibility in the conversion process.

**Comment by lainosantos** [comment]
Hi @jtojnar.

Version 0.5.0 has been released with support to remove the converted files with clear command, you can use it to clear the source directory before moving the converted files.

About the test phpt files, you can exclude them from the conversion and just apply a rename command in the tests directory so that the class names are updated.

I'm considering this issue as resolved.

**Comment by jtojnar** [comment]
Thanks I have settled on the following workflow:

1. Install the tool.
	```
	composer create-project lesphp/psr4-converter
	```

2. Create the map.
	```
	psr4-converter/bin/psr4-converter map -m /tmp/.psr4-converter.json --underscore-conversion --ignore-namespaced-underscore --ignore-path="bootstrap.php" --path-based-conversion --force-names-camelcase -- "App" app/
	```

3. Create transformed files in the new temporary directory.
	```
	psr4-converter/bin/psr4-converter convert /tmp/.psr4-converter.json --ignore-vendor-path --allow-risky -- app2/
	```

4. Commit renames separately so that Git can track them.
	1. Copy the original files as targets.
		```
		jq --raw-output '
			.srcPath as $app
			| .files
			| map(.units[])
			| map(
				($app + "/" + .targetFileWithoutVendor) as $targetFile
				| "mkdir -p \"$(dirname " + ($targetFile|@sh) + ")\""
					+ "\n" + "cp " + (.originalFile|@sh) + " " + ($targetFile|@sh)
			)
			| join("\n")' /tmp/.psr4-converter.json | sh -
		```
	2. Clear the original ones.
		```
		psr4-converter/bin/psr4-converter clear --dry-run /tmp/.psr4-converter.json
		```
	3. Stage the changes in `app/`
		```
		git add app/
		```
	4. Commit the changes.
		```
		git commit -m 'Rename files before PSR-4 conversion
		
		So that Git can track the renames.'
		```

	> **Note** This step does not move non-PHP files so that will need to be done manually.

	> **Warning** If there are multiple units (e.g. classes) in a single source file, this will create duplicate files.
5. Replace the renamed files with the converted ones:
	```
	cp -r app2/* app/
	rm -r app2
	```

6. Update references in tests:
	```
	psr4-converter/bin/psr4-converter rename /tmp/.psr4-converter.json tests/
	```

7. Run PHP-CS-Fixer and manually revert formatting changes caused by codegen.
8. Commit the changes.
