### ISSUE TITLE
Locate autoloader.php using composer global

### ISSUE THREAD

**Issue by JJCLane** [lesphp/psr4-converter#2]
As of Composer 2.2 it's possible to [find the `autoloader.php` file automatically](https://getcomposer.org/doc/articles/vendor-binaries.md#finding-the-composer-autoloader-from-a-binary). 

When trying to run after installing globally I ran into this error:
```
Warning: Undefined global variable $_composer_autoload_path in /root/.composer/vendor/lesphp/psr4-converter/bin/psr4-converter.php on line 15

Fatal error: Uncaught ValueError: Path cannot be empty in /root/.composer/vendor/lesphp/psr4-converter/bin/psr4-converter.php:15
Stack trace:
#0 {main}
  thrown in /root/.composer/vendor/lesphp/psr4-converter/bin/psr4-converter.php on line 15
```

**Comment by lainosantos** [comment]
Hello, @JJCLane .

This issue was fixed on release 0.5.1
